/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiOrdersRouteImport } from './routes/api.orders'
import { Route as ApiAdminAuthRouteImport } from './routes/api.admin-auth'
import { Route as ApiProductsIdRouteImport } from './routes/api.products.$id'
import { Route as ApiOrdersIdRouteImport } from './routes/api.orders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin-auth',
  path: '/api/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/api/admin-auth'
    | '/api/orders'
    | '/api/products'
    | '/api/profile'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/orders/$id'
    | '/products/$productId'
    | '/api/orders/$id'
    | '/api/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/api/admin-auth'
    | '/api/orders'
    | '/api/products'
    | '/api/profile'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/orders/$id'
    | '/products/$productId'
    | '/api/orders/$id'
    | '/api/products/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/api/admin-auth'
    | '/api/orders'
    | '/api/products'
    | '/api/profile'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/orders/$id'
    | '/products/$productId'
    | '/api/orders/$id'
    | '/api/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiProfileRoute: typeof ApiProfileRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-auth': {
      id: '/api/admin-auth'
      path: '/api/admin-auth'
      fullPath: '/api/admin-auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ApiOrdersRouteChildren {
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersIdRoute: ApiOrdersIdRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiProfileRoute: ApiProfileRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
